name: CI

on:
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: {node-version: 13.x}
      - run: yarn install
      - run: yarn build
      - run: yarn deploy